name: Sync to Gitee

on:
  push:
    branches:
      - main  # ⚠️請確認你的預設分支是 main 還是 master，需與網頁顯示的一致

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the GitHub repos to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/${{ github.repository_owner }}
          dst: gitee/${{ secrets.GITEE_USER }}
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "${{ github.event.repository.name }}"
          force_update: true
